---
- name: group
  group: name=alilab
- name: Add the user
  user:
    name: alilab
    groups: alilab
    createhome: yes
    home: /home/alilab
    password: alilab
    shell: /bin/bash
- name: change passwd
  #shell: "echo 'alilab:ailab' | sudo chpasswd"
  shell: "echo alilab | passwd --stdin alilab"
- name : docker group
  shell: | 
     cmd:
     usermod -aG docker alilab
     docker pull osixia/openldap:1.3.0
- name: alilab user
  template: 
      src: test.sh
      dest: /home/alilab
      owner: root
      group: root
      mode: '0755'

